"""Large hand-curated scene-pocket corpus for training retrieval/decide.

Compact bundles: one card + one moment + one digest each. Goal: 50+ digests
when combined with SEED_BUNDLES + EXTRA_BUNDLES.
"""
from __future__ import annotations

from typing import Any


def _pocket(
    *,
    slug: str,
    title: str,
    year: int,
    directors: list[str],
    genres: list[str],
    tier: str,
    theme: str,
    logline: str,
    slugline: str,
    card_title: str,
    what: str,
    spine: str,
    tags: list[str],
    scale: str,
    subject: str,
    action: str,
    mood: str,
    situation: str,
    decision: str,
    rationale: str,
    phase: str = "shotlist",
    structural_beat: str = "Catalyst",
    characters: list[str] | None = None,
    medium: str = "short",
) -> dict[str, Any]:
    chars = characters or ["PROTAG"]
    return {
        "work": {
            "slug": slug,
            "title": title,
            "year": year,
            "directors": directors,
            "genres": genres,
            "medium": medium,
            "tier": tier,
            "theme": theme,
            "logline": logline,
            "plot_summary": what,
            "source": "seed:hand-labeled-scale",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": slugline,
            "title": card_title,
            "what_happens": what,
            "relationship_delta": "Shift under pressure.",
            "plot_function": "Craft pocket for retrieval.",
            "emotional_spine": spine,
            "characters": chars,
            "structural_beat": structural_beat,
            "act": 1,
            "tags": tags,
        }],
        "shot_moments": [{
            "idx": 0,
            "scene_idx": 0,
            "start_s": 0.0,
            "end_s": 6.0,
            "scale": scale,
            "subject": subject,
            "angle": "EYE LEVEL",
            "move": "STATIC",
            "int_ext": slugline.split()[0] if slugline else "INT.",
            "location": "SET",
            "time_of_day": "DAY" if "DAY" in slugline else "NIGHT",
            "action_text": action,
            "characters": chars,
            "mood": mood,
            "dialogue": [],
        }],
        "decision_digests": [{
            "scene_idx": 0,
            "shot_idx": 0,
            "situation": situation,
            "decision": decision,
            "rationale": rationale,
            "director": directors[0] if directors else "unknown",
            "tags": tags,
            "phase": phase,
        }],
    }


# ~40 compact pockets across genres/styles for hybrid lookup density.
SCALE_BUNDLES: list[dict[str, Any]] = [
    _pocket(
        slug="scale-otazu-rain", title="Rain on Glass (S)", year=2003,
        directors=["Wong Kar-wai"], genres=["romance", "drama"], tier="S",
        theme="Longing as weather", logline="Two people miss each other by a pane of rain.",
        slugline="INT. APARTMENT - NIGHT", card_title="Rain glass",
        what="PROTAG watches rain on glass; lover's silhouette blurs outside.",
        spine="Melancholy distance", tags=["rain", "glass", "silhouette", "longing"],
        scale="CU", subject="RAIN ON GLASS", action="Focus rack from drops to silhouette; hold.",
        mood="saturated neon rain", situation="Romance beat; temptation to cut to dialogue.",
        decision="Hold CU on rain-glass until the silhouette leaves; no dialogue.",
        rationale="Distance is the love story.",
    ),
    _pocket(
        slug="scale-kubrick-symmetry", title="Corridor Symmetry (S)", year=1980,
        directors=["Stanley Kubrick"], genres=["horror", "thriller"], tier="S",
        theme="Order as threat", logline="A hallway that is too perfect.",
        slugline="INT. HOTEL CORRIDOR - DAY", card_title="Perfect hall",
        what="CHILD rides into vanishing-point symmetry; adult watches from frame edge.",
        spine="Sterile dread", tags=["symmetry", "corridor", "oners", "geometry"],
        scale="WS", subject="CORRIDOR", action="Centered track; vanish point holds the child.",
        mood="clinical carpet", situation="Horror entry; editor wants handheld chaos.",
        decision="Lock symmetry; slow center-line track; refuse handheld.",
        rationale="Geometry is the monster.",
    ),
    _pocket(
        slug="scale-malick-magic-hour", title="Magic Hour Field (S)", year=2011,
        directors=["Terrence Malick"], genres=["drama", "war"], tier="S",
        theme="Grace in violence", logline="Soldiers in gold light before the cut of war.",
        slugline="EXT. FIELD - DUSK", card_title="Golden field",
        what="SOLDIERS walk through tall grass; light dies on faces.",
        spine="Sacred dread", tags=["magic hour", "grass", "silhouette", "war"],
        scale="WS", subject="FIELD", action="Wide late-day; faces last; no reverse yet.",
        mood="amber hush", situation="War film; pressure to start gunfire early.",
        decision="Hold magic-hour wide until light fails; violence after the cut.",
        rationale="Beauty indicts what follows.",
    ),
    _pocket(
        slug="scale-pta-long-take", title="Doorway Long Take (S)", year=2007,
        directors=["Paul Thomas Anderson"], genres=["drama"], tier="S",
        theme="Power enters a room", logline="A man arrives; the room rearranges around him.",
        slugline="INT. LIVING ROOM - DAY", card_title="Arrival",
        what="CHARISMATIC enters; family freezes; camera drifts with social gravity.",
        spine="Charismatic threat", tags=["long take", "entrance", "blocking"],
        scale="MS", subject="DOORWAY", action="Single take entrance; reframe by blocking only.",
        mood="dusty domestic", situation="Entrance scene; coverage temptation.",
        decision="One fluid take; power shown by who yields space.",
        rationale="Coverage would dilute the social physics.",
        characters=["CHARISMATIC", "FAMILY"],
    ),
    _pocket(
        slug="scale-scorsese-voiceover", title="Voiceover Street (S)", year=1990,
        directors=["Martin Scorsese"], genres=["crime", "drama"], tier="S",
        theme="Seduction of the life", logline="Narration glories what the image condemns.",
        slugline="EXT. STREET - NIGHT", card_title="The walk",
        what="PROTAG walks; VO boasts; camera thrills then tightens.",
        spine="Cocky dread", tags=["voiceover", "tracking", "crime"],
        scale="MS", subject="WALK", action="Steadicam walk; VO rides the move; end on still face.",
        mood="night neon grit", situation="Crime open; VO feels expositional.",
        decision="Keep VO; counterpoint with image that undercuts the boast.",
        rationale="Irony is the moral stance.",
    ),
    _pocket(
        slug="scale-nolan-parallel", title="Parallel Cut Board (A)", year=2010,
        directors=["Christopher Nolan"], genres=["thriller", "sci-fi"], tier="A",
        theme="Time as montage", logline="Three clocks tick toward one detonation of meaning.",
        slugline="INT./EXT. MULTIPLE - DAY", card_title="Triptych time",
        what="Three actions cut in rising tempo toward a shared beat.",
        spine="Cognitive thrill", tags=["parallel cut", "tempo", "clocks"],
        scale="MS", subject="ACTION A/B/C", action="Cross-cut on rising rhythm; land on shared sound.",
        mood="metallic urgency", situation="Complex plot; fear of confusion.",
        decision="Bind strands with one sonic event; cut on tempo not explanation.",
        rationale="Clarity is rhythmic, not expository.",
        characters=["A", "B", "C"],
    ),
    _pocket(
        slug="scale-villeneuve-scale", title="Monument Scale (S)", year=2021,
        directors=["Denis Villeneuve"], genres=["sci-fi", "drama"], tier="S",
        theme="Human smallness", logline="A figure against architecture that ends thought.",
        slugline="EXT. DESERT STRUCTURE - DAY", card_title="Ant under god",
        what="PROTAG approaches a vast structure; wind and scale dominate.",
        spine="Awe", tags=["scale", "wide", "sci-fi", "silence"],
        scale="EWS", subject="STRUCTURE", action="Extreme wide; figure tiny; hold before CU.",
        mood="hot silence", situation="Sci-fi; pressure for dialogue to explain lore.",
        decision="No dialogue until scale is felt; EWS before any face CU.",
        rationale="Awe first; lore later.",
    ),
    _pocket(
        slug="scale-tarantino-trunk", title="Trunk POV (S)", year=1994,
        directors=["Quentin Tarantino"], genres=["crime", "comedy"], tier="S",
        theme="Genre as joke and threat", logline="Looking up from the dark at two killers.",
        slugline="EXT. TRUNK - DAY", card_title="Up from dark",
        what="Two men look down into trunk; banter; sunlight halos them.",
        spine="Comic menace", tags=["trunk POV", "low angle", "banter"],
        scale="LA", subject="TWO MEN", action="Low angle from trunk; hold through banter beat.",
        mood="hard sun", situation="Crime comedy; want coverage of both faces.",
        decision="Stay trunk-POV until lid slam; faces only as silhouettes of power.",
        rationale="POV is the gag and the threat.",
        characters=["HITMAN A", "HITMAN B"],
    ),
    _pocket(
        slug="scale-coen-empty-road", title="Empty Road Wide (S)", year=2007,
        directors=["Joel Coen", "Ethan Coen"], genres=["thriller", "crime"], tier="S",
        theme="Fate in landscape", logline="A car on a road that does not care.",
        slugline="EXT. HIGHWAY - DAY", card_title="Flat road",
        what="CAR inches on flat prairie; wind; no music.",
        spine="Cosmic indifference", tags=["wide", "landscape", "car", "silence"],
        scale="EWS", subject="ROAD", action="Static wide; car small; hold longer than comfort.",
        mood="bleak noon", situation="Thriller open; urge to start score.",
        decision="Mute score; hold empty wide until cut on car pass.",
        rationale="Landscape is the antagonist.",
    ),
    _pocket(
        slug="scale-bong-class-stair", title="Stair Class Cut (S)", year=2019,
        directors=["Bong Joon-ho"], genres=["thriller", "drama"], tier="S",
        theme="Vertical class", logline="A staircase that is a social ladder.",
        slugline="INT. HOUSE STAIR - DAY", card_title="Down the house",
        what="FAMILY moves down floors; light and sound degrade with class descent.",
        spine="Satirical dread", tags=["stairs", "class", "sound design"],
        scale="MS", subject="STAIR", action="Descending stages; design and audio shift each landing.",
        mood="polished to damp", situation="Class theme; fear of being on-the-nose.",
        decision="Let architecture and sound mark class; minimal dialogue about money.",
        rationale="Space is ideology.",
        characters=["FAMILY"],
    ),
    _pocket(
        slug="scale-refn-neon-face", title="Neon Face Hold (S)", year=2011,
        directors=["Nicolas Winding Refn"], genres=["thriller", "crime"], tier="S",
        theme="Beauty as violence", logline="A face painted by neon before the hit.",
        slugline="INT. CLUB - NIGHT", card_title="Neon mask",
        what="DRIVER sits; magenta/cyan wash; eyes unblinking.",
        spine="Icy cool", tags=["neon", "CU", "silence", "color"],
        scale="CU", subject="FACE", action="Static CU under shifting neon; no blink cut.",
        mood="synth noir", situation="Action film; expect kinetic open.",
        decision="Still CU; color does the motion; delay the violence.",
        rationale="Icon first.",
    ),
    _pocket(
        slug="scale-arranofsky-snorricam", title="Snorri Addiction (A)", year=2000,
        directors=["Darren Aronofsky"], genres=["drama"], tier="A",
        theme="Subjective spiral", logline="Camera bolted to the addict's chest.",
        slugline="INT. APARTMENT - NIGHT", card_title="Body cam dread",
        what="PROTAG storms rooms; world shakes with breath and pulse.",
        spine="Panic intimacy", tags=["snorricam", "subjective", "addiction"],
        scale="MS", subject="PROTAG", action="Snorri/body-mount; environment slides around face.",
        mood="sick fluorescent", situation="Addiction scene; temptation of beautiful composition.",
        decision="Ugly subjective mount; prioritize breath rhythm over beauty.",
        rationale="Form is the disease.",
    ),
    _pocket(
        slug="scale-lynch-corridor-hum", title="Hum Corridor (S)", year=2001,
        directors=["David Lynch"], genres=["mystery", "thriller"], tier="S",
        theme="Domestic uncanny", logline="A hallway that hums wrong.",
        slugline="INT. HALLWAY - NIGHT", card_title="Wrong hum",
        what="PROTAG pauses mid-hall; low industrial hum rises; lights flicker.",
        spine="Uncanny calm", tags=["sound design", "hallway", "uncanny"],
        scale="MS", subject="HALL", action="Slow push; sound leads; cut on light flicker.",
        mood="brown velvet night", situation="Mystery; pressure to explain supernatural.",
        decision="No explanation; sound and light do the dread.",
        rationale="Uncanny dies when named.",
    ),
    _pocket(
        slug="scale-anderson-tableau", title="Centered Tableau (S)", year=2014,
        directors=["Wes Anderson"], genres=["comedy", "drama"], tier="S",
        theme="Order as affection", logline="A family posed like a stamp.",
        slugline="INT. HOTEL LOBBY - DAY", card_title="Stamp family",
        what="FAMILY lined symmetrically; tiny gestures break the pattern.",
        spine="Wry tenderness", tags=["tableau", "symmetry", "comedy"],
        scale="WS", subject="FAMILY", action="Dead-center tableau; allow one off-pattern twitch.",
        mood="pastel crisp", situation="Comedy; fear of flatness.",
        decision="Hold formal tableau; humor is the micro-break in symmetry.",
        rationale="Rigidity is the joke.",
        characters=["FAMILY"],
    ),
    _pocket(
        slug="scale-spielberg-face-reveal", title="Wonder Face (S)", year=1977,
        directors=["Steven Spielberg"], genres=["sci-fi", "adventure"], tier="S",
        theme="Awe through faces", logline="We see wonder before the wonder.",
        slugline="EXT. FIELD - NIGHT", card_title="Look up",
        what="FACES tilt up in light; we delay the object of their gaze.",
        spine="Childlike awe", tags=["face gallery", "reveal delay", "wonder"],
        scale="CU", subject="FACES", action="Montage of reaction faces; withhold reverse long.",
        mood="warm key from sky", situation="Spectacle; urge to show VFX early.",
        decision="Faces first, reverse last; sell awe before object.",
        rationale="Wonder is human, not CGI.",
        characters=["CROWD"],
    ),
    _pocket(
        slug="scale-scott-smoke-shaft", title="Smoke Shaft (S)", year=1979,
        directors=["Ridley Scott"], genres=["sci-fi", "horror"], tier="S",
        theme="Industrial sublime", logline="Light shafts cut smoke like knives.",
        slugline="INT. SHIP CORRIDOR - NIGHT", card_title="God rays grit",
        what="CREW walks into volumetric light; sweat and particles.",
        spine="Claustrophobic awe", tags=["volumetric light", "smoke", "sci-fi"],
        scale="MS", subject="CORRIDOR", action="Side light shafts; slow walk; haze thick.",
        mood="oily blue", situation="Horror sci-fi; dark underexposure risk.",
        decision="Carve shape with smoke and shaft light; faces last.",
        rationale="Atmosphere is architecture.",
        characters=["CREW"],
    ),
    _pocket(
        slug="scale-fincher-insert-hand", title="Precision Insert (S)", year=2010,
        directors=["David Fincher"], genres=["thriller", "drama"], tier="S",
        theme="Control in detail", logline="A hand places a paper with surgical care.",
        slugline="INT. OFFICE - DAY", card_title="The insert",
        what="HAND aligns document; click of pen; face still offscreen.",
        spine="Cold precision", tags=["insert", "hands", "procedure"],
        scale="ECU", subject="HANDS", action="Macro insert of placement; diegetic click as cut cue.",
        mood="cool gray", situation="Thriller; fear of over-cutting inserts.",
        decision="One clean insert as character; hold until placement perfect.",
        rationale="Process is psychology.",
    ),
    _pocket(
        slug="scale-zhao-horizon", title="Horizon Quiet (S)", year=2020,
        directors=["Chloé Zhao"], genres=["drama"], tier="S",
        theme="Dignity in vastness", logline="A life against open land.",
        slugline="EXT. PLAINS - DAY", card_title="Open land",
        what="PROTAG walks; wind; distant highway murmur.",
        spine="Quiet resilience", tags=["landscape", "naturalism", "wide"],
        scale="WS", subject="PLAINS", action="Wide natural light; walk duration real.",
        mood="dust light", situation="Drama; urge to score sentiment.",
        decision="No score; diegetic wind only; length of walk is the emotion.",
        rationale="Time is empathy.",
    ),
    _pocket(
        slug="scale-pearce-color-split", title="Split Color Night (A)", year=2016,
        directors=["Nicolas Winding Refn"], genres=["thriller"], tier="A",
        theme="Duality in gel", logline="Warm and cold split a face at night.",
        slugline="INT. CAR - NIGHT", card_title="Two gels",
        what="DRIVER lit half amber half cyan; city streaks.",
        spine="Fractured cool", tags=["color split", "car", "night"],
        scale="CU", subject="DRIVER", action="Static CU with hard color split; no fill.",
        mood="candy noir", situation="Night drive; soft beauty light temptation.",
        decision="Hard two-color split; refuse soft beauty fill.",
        rationale="Color is psychology.",
    ),
    _pocket(
        slug="scale-kurosawa-rain-battle", title="Rain Battle Wide (S)", year=1985,
        directors=["Akira Kurosawa"], genres=["action", "drama"], tier="S",
        theme="Chaos composed", logline="Armies in rain; mud as destiny.",
        slugline="EXT. BATTLEFIELD - DAY", card_title="Mud rain",
        what="ARMIES collide in downpour; banners and mud.",
        spine="Epic futility", tags=["rain", "battle", "wide", "mud"],
        scale="EWS", subject="ARMIES", action="Epic wide in rain; telephoto crush later.",
        mood="gray deluge", situation="Action; modern fast coverage pressure.",
        decision="Epic wides first; let rain unify chaos before tight cuts.",
        rationale="Weather is the editor.",
        characters=["ARMY A", "ARMY B"],
    ),
    _pocket(
        slug="scale-hitchcock-stairs", title="Stair Subjective (S)", year=1958,
        directors=["Alfred Hitchcock"], genres=["thriller"], tier="S",
        theme="Vertigo of guilt", logline="A staircase that won't stay still.",
        slugline="INT. TOWER STAIR - DAY", card_title="The drop",
        what="PROTAG looks down spiral; space stretches.",
        spine="Nauseous fear", tags=["dolly zoom", "stairs", "subjective"],
        scale="POV", subject="STAIRWELL", action="Dolly zoom / stretch POV; hold on gut reaction.",
        mood="sick daylight", situation="Thriller; CG excess temptation.",
        decision="Subjective optical stretch; cut to face only after space warps.",
        rationale="Fear is perceptual.",
    ),
    _pocket(
        slug="scale-coppola-doorway", title="Godfather Door (S)", year=1972,
        directors=["Francis Ford Coppola"], genres=["crime", "drama"], tier="S",
        theme="Power closes the door", logline="A door that ends innocence.",
        slugline="INT. OFFICE - DAY", card_title="Door closes",
        what="WIFE watches door shut on men and business; she is excluded.",
        spine="Tragic exclusion", tags=["doorway", "blocking", "power"],
        scale="MS", subject="DOOR", action="Frame wife foreground; door closes mid-shot.",
        mood="warm brown dark", situation="Crime drama; urge to follow men inside.",
        decision="Stay with excluded character; door is the cut.",
        rationale="Power is who remains outside.",
        characters=["WIFE", "MEN"],
    ),
    _pocket(
        slug="scale-lee-spike-dutch", title="Dutch Argument (A)", year=1989,
        directors=["Spike Lee"], genres=["drama"], tier="A",
        theme="Heat of rhetoric", logline="An argument that tilts the world.",
        slugline="EXT. STREET - DAY", card_title="Tilt talk",
        what="TWO face off; camera dutch as rhetoric escalates.",
        spine="Public fury", tags=["dutch angle", "argument", "street"],
        scale="MS", subject="TWO", action="Increasing dutch; keep eyelines sharp.",
        mood="hot summer", situation="Dialogue heavy; coverage grid temptation.",
        decision="Let angle escalate with language; one axis of tilt.",
        rationale="Form is politics.",
        characters=["A", "B"],
    ),
    _pocket(
        slug="scale-miyazaki-wind", title="Wind Through Grass (S)", year=1988,
        directors=["Hayao Miyazaki"], genres=["animation", "adventure"], tier="S",
        theme="Living air", logline="Wind as character before any human speaks.",
        slugline="EXT. MEADOW - DAY", card_title="Living wind",
        what="Grass and clouds move; CHILD enters late.",
        spine="Gentle wonder", tags=["wind", "nature", "animation"],
        scale="WS", subject="MEADOW", action="Wind-driven motion first; human enter late.",
        mood="clear air", situation="Adventure open; plot dump pressure.",
        decision="Establish living world via wind; dialogue after nature breathes.",
        rationale="Worldhood before quest.",
        characters=["CHILD"],
    ),
    _pocket(
        slug="scale-bergman-faces", title="Two Faces Merge (S)", year=1966,
        directors=["Ingmar Bergman"], genres=["drama"], tier="S",
        theme="Identity bleed", logline="Two faces share one frame until they are one.",
        slugline="INT. ROOM - DAY", card_title="Merge",
        what="WOMAN A and WOMAN B faces split/merge in close study.",
        spine="Psychological fusion", tags=["faces", "split screen", "identity"],
        scale="CU", subject="FACES", action="Composite or matched CU; long hold.",
        mood="soft gray", situation="Psychodrama; fear of stillness.",
        decision="Still dual CU; refuse coverage that separates them early.",
        rationale="Identity is compositional.",
        characters=["WOMAN A", "WOMAN B"],
    ),
    _pocket(
        slug="scale-tarkovsky-candle", title="Candle Walk (S)", year=1983,
        directors=["Andrei Tarkovsky"], genres=["drama"], tier="S",
        theme="Faith as duration", logline="A candle crossing a pool is the plot.",
        slugline="INT. RUIN - DAY", card_title="Candle",
        what="MAN carries candle across water; fails; tries again.",
        spine="Sacred patience", tags=["long take", "candle", "ritual"],
        scale="WS", subject="MAN + CANDLE", action="Long take attempt; cut only on failure/reset.",
        mood="damp stone", situation="Art film; modern pace pressure.",
        decision="Duration is meaning; fail and repeat without montage shortcuts.",
        rationale="Time is belief.",
    ),
    _pocket(
        slug="scale-park-hallway-color", title="Hallway Color Hit (S)", year=2003,
        directors=["Park Chan-wook"], genres=["thriller"], tier="S",
        theme="Revenge as design", logline="A corridor that becomes a color field of violence.",
        slugline="INT. CORRIDOR - NIGHT", card_title="Color corridor",
        what="FIGHT spills; wardrobe and gel turn hall into graphic panel.",
        spine="Operatic rage", tags=["corridor", "color", "action"],
        scale="WS", subject="CORRIDOR FIGHT", action="Graphic wide; color blocks action beats.",
        mood="crimson design", situation="Action; gritty realism pressure.",
        decision="Stylize: color fields and wide graphic staging over shaky chaos.",
        rationale="Revenge is aesthetic.",
        characters=["AVENGER", "FOE"],
    ),
    _pocket(
        slug="scale-linklater-walk-talk", title="Walk and Talk Dawn (S)", year=1995,
        directors=["Richard Linklater"], genres=["romance", "drama"], tier="S",
        theme="Time as conversation", logline="Two people walk until night becomes morning.",
        slugline="EXT. CITY - NIGHT", card_title="Walk talk",
        what="TWO walk and talk; locations change; idea is the cut.",
        spine="Intimate intellect", tags=["walk and talk", "long scene", "romance"],
        scale="MS", subject="TWO", action="Side-by-side track; locations mark time.",
        mood="blue hour to gold", situation="Romance; plot event pressure.",
        decision="No plot event; geography changes only as time marker.",
        rationale="Talk is action.",
        characters=["A", "B"],
    ),
    _pocket(
        slug="scale-demme-silence-lambs", title="Center Look (S)", year=1991,
        directors=["Jonathan Demme"], genres=["thriller", "horror"], tier="S",
        theme="Eye contact as power", logline="A look straight into us.",
        slugline="INT. PRISON - DAY", card_title="Into lens",
        what="ANTAGONIST speaks into lens; interrogator off-axis elsewhere.",
        spine="Intimate menace", tags=["center look", "POV", "dialogue"],
        scale="CU", subject="ANTAGONIST", action="Direct-to-lens CU; reverse more conventional.",
        mood="cold institutional", situation="Dialogue; both center-look overuse risk.",
        decision="Only predator gets lens; prey stays off-axis reverse.",
        rationale="Eye contact is hierarchy.",
        characters=["ANTAGONIST", "AGENT"],
    ),
    _pocket(
        slug="scale-burton-expressionist", title="Crooked Set (A)", year=1990,
        directors=["Tim Burton"], genres=["fantasy", "comedy"], tier="A",
        theme="Interior as architecture", logline="A room that looks like a mood.",
        slugline="INT. ATTIC - NIGHT", card_title="Crooked room",
        what="PROTAG enters skewed attic; shadows cartoon-hard.",
        spine="Gothic whimsy", tags=["expressionist", "set design", "shadow"],
        scale="WS", subject="ATTIC", action="Wide to show design; then enter character.",
        mood="inky silhouette", situation="Fantasy; CG set extension temptation.",
        decision="Practical crooked set; design reads in wide before face work.",
        rationale="World is character.",
    ),
    _pocket(
        slug="scale-bigelow-hud-chaos", title="HUD Chaos (S)", year=2008,
        directors=["Kathryn Bigelow"], genres=["war", "thriller"], tier="S",
        theme="Fog of war", logline="Information overload as combat.",
        slugline="INT. COMMAND - NIGHT", card_title="Screens",
        what="OPERATORS watch multi-feeds; audio stacks; decision under noise.",
        spine="Anxious focus", tags=["screens", "war", "montage audio"],
        scale="MS", subject="SCREENS", action="Cut among feeds; keep one face anchor.",
        mood="blue monitor", situation="War tech; clear single feed temptation.",
        decision="Stack competing feeds; clarity only at decision beat.",
        rationale="Confusion is truth of modern war.",
        characters=["OPERATORS"],
    ),
    _pocket(
        slug="scale-eggers-period-candle", title="Candle Only Night (S)", year=2015,
        directors=["Robert Eggers"], genres=["horror", "drama"], tier="S",
        theme="Period light as law", logline="Night lit only by what they could burn.",
        slugline="INT. CABIN - NIGHT", card_title="True dark",
        what="FAMILY around single candle; faces fall into true black.",
        spine="Puritan dread", tags=["candlelight", "period", "dark"],
        scale="MS", subject="TABLE", action="Practical candle key; crush blacks; no fill.",
        mood="amber void", situation="Horror; modern lift of shadows temptation.",
        decision="Respect period darkness; no modern fill; eyes find light.",
        rationale="Light is historical.",
        characters=["FAMILY"],
    ),
    _pocket(
        slug="scale-gerwig-snap-zoom", title="Pastel Snap Zoom (A)", year=2017,
        directors=["Greta Gerwig"], genres=["comedy", "drama"], tier="A",
        theme="Coming-of-age energy", logline="A thought lands with a snap zoom.",
        slugline="EXT. STREET - DAY", card_title="Snap idea",
        what="PROTAG gets an idea mid-walk; snap zoom on face.",
        spine="Bright urgency", tags=["snap zoom", "comedy", "youth"],
        scale="MS", subject="PROTAG", action="Walk MS to snap CU on realization.",
        mood="sun pastel", situation="Comedy; overuse of zooms risk.",
        decision="One motivated snap zoom as punctuation; then hold.",
        rationale="Punctuation not style soup.",
    ),
    _pocket(
        slug="scale-cuaron-oner-birth", title="Oner Through Rooms (S)", year=2006,
        directors=["Alfonso Cuarón"], genres=["drama", "sci-fi"], tier="S",
        theme="Life continues", logline="A long take through chaos and intimacy.",
        slugline="INT. BUILDING - DAY", card_title="Through rooms",
        what="CAMERA drifts rooms as crisis and tenderness coexist.",
        spine="Human continuum", tags=["oner", "blocking", "long take"],
        scale="MS", subject="ROOMS", action="Continuous move; reframe by architecture.",
        mood="dust daylight", situation="Drama; coverage safety net temptation.",
        decision="Commit to oner; design blocking so emotion peaks mid-move.",
        rationale="Time unbroken is life.",
        characters=["PROTAG", "OTHERS"],
    ),
    _pocket(
        slug="scale-rei-wet-street", title="Wet Street Noir (A)", year=1940,
        directors=["John Huston"], genres=["noir", "crime"], tier="A",
        theme="Fate on wet asphalt", logline="A man walks streets that shine like guilt.",
        slugline="EXT. STREET - NIGHT", card_title="Wet asphalt",
        what="DETECTIVE walks reflections; neon smears.",
        spine="Hardboiled loneliness", tags=["noir", "wet street", "night"],
        scale="WS", subject="STREET", action="Low wet reflections; figure mid-frame.",
        mood="black mirror street", situation="Noir; dry clean street practicality.",
        decision="Wet down street; reflections sell noir more than hat angles.",
        rationale="Texture is genre.",
    ),
    _pocket(
        slug="scale-campion-hand-touch", title="Glove Touch (S)", year=1993,
        directors=["Jane Campion"], genres=["drama", "romance"], tier="S",
        theme="Desire in gesture", logline="A touch through fabric is the scene.",
        slugline="EXT. BEACH - DAY", card_title="Through glove",
        what="HANDS almost touch; fabric and skin negotiate.",
        spine="Repressed heat", tags=["hands", "insert", "desire"],
        scale="ECU", subject="HANDS", action="Insert of near-touch; faces deferred.",
        mood="cool daylight", situation="Romance; face coverage default.",
        decision="Hands first; faces only after touch registers.",
        rationale="Desire is tactile.",
        characters=["A", "B"],
    ),
    _pocket(
        slug="scale-reid-car-night", title="Car Dialogue Night (A)", year=2013,
        directors=["Jeff Nichols"], genres=["thriller", "drama"], tier="A",
        theme="Pressure in a cabin", logline="Two men in a car; the road is a timer.",
        slugline="INT. CAR - NIGHT", card_title="Cabin talk",
        what="TWO talk while driving; dashboard light only.",
        spine="Quiet pressure", tags=["car", "dialogue", "practical light"],
        scale="MS", subject="TWO", action="Over dash practicals; rare exterior flash.",
        mood="green dash", situation="Dialogue; boredom fear.",
        decision="Stay in car; exteriors only as punctuation; light is dashboard.",
        rationale="Containment is tension.",
        characters=["A", "B"],
    ),
    _pocket(
        slug="scale-jenkins-skin-light", title="Skin Light Quiet (S)", year=2016,
        directors=["Barry Jenkins"], genres=["drama", "romance"], tier="S",
        theme="Tenderness as light", logline="Light loves the skin before anyone speaks.",
        slugline="INT. BEDROOM - NIGHT", card_title="Soft skin",
        what="TWO in soft practicals; silence holds.",
        spine="Tender awe", tags=["soft light", "skin", "quiet"],
        scale="CU", subject="FACES", action="Soft key on skin; long quiet before line.",
        mood="warm amber soft", situation="Romance; dialogue fill silence fear.",
        decision="Hold silence under beautiful light; speech last.",
        rationale="Light is the love scene.",
        characters=["A", "B"],
    ),
    _pocket(
        slug="scale-chandor-ocean-wide", title="Ocean Alone Wide (S)", year=2013,
        directors=["J.C. Chandor"], genres=["drama", "thriller"], tier="S",
        theme="Isolation scale", logline="A man, a boat, an ocean that wins.",
        slugline="EXT. OCEAN - DAY", card_title="Spec on sea",
        what="BOAT alone; horizon empty; weather builds.",
        spine="Existential solitude", tags=["ocean", "wide", "isolation"],
        scale="EWS", subject="BOAT", action="Aerial/wide ocean; boat as speck.",
        mood="steel blue", situation="Survival; tight coverage early temptation.",
        decision="Establish oceanic scale first; face CU earned after emptiness.",
        rationale="Antagonist is scale.",
    ),
    _pocket(
        slug="scale-pearl-split-diopter", title="Split Diopter Threat (A)", year=1976,
        directors=["Brian De Palma"], genres=["thriller", "horror"], tier="A",
        theme="Two planes of danger", logline="Foreground and background both loaded.",
        slugline="INT. HOUSE - DAY", card_title="Two planes",
        what="OBJECT sharp fg; figure sharp bg; both threaten.",
        spine="Paranoid clarity", tags=["split diopter", "thriller", "deep focus"],
        scale="MS", subject="FG/BG", action="Split diopter hold; refuse rack focus.",
        mood="sunny menace", situation="Thriller; modern rack-focus default.",
        decision="Split diopter so both threats stay sharp; no rack rescue.",
        rationale="Paranoia sees everything.",
        characters=["PROTAG", "THREAT"],
    ),
    _pocket(
        slug="scale-reichardt-river", title="River Walk Quiet (S)", year=2010,
        directors=["Kelly Reichardt"], genres=["drama", "western"], tier="S",
        theme="Patience of land", logline="Walking is the plot.",
        slugline="EXT. RIVER - DAY", card_title="Along water",
        what="TRAVELERS walk riverbank; ambient only.",
        spine="Stoic fatigue", tags=["walking", "ambient", "landscape"],
        scale="WS", subject="RIVERBANK", action="Long walk duration; ambient river bed.",
        mood="overcast soft", situation="Western; score heroism pressure.",
        decision="No heroic score; walk length is character.",
        rationale="Endurance cinema.",
        characters=["TRAVELERS"],
    ),
]
