"""Additional hand-labeled S/A-tier scene pockets for corpus scale."""
from __future__ import annotations

EXTRA_BUNDLES: list[dict] = [
    {
        "work": {
            "slug": "western-standoff",
            "title": "Western Standoff (synthetic S-tier)",
            "year": 1966,
            "directors": ["Sergio Leone"],
            "genres": ["western", "thriller"],
            "medium": "short",
            "tier": "S",
            "theme": "Myth through eyes and waiting",
            "logline": "Three men wait; the cut is the gunfight.",
            "plot_summary": "Extreme close-ups and silence before violence.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "EXT. PLAZA - DAY",
            "title": "The wait",
            "what_happens": "Three gunfighters face each other. Wind. Eyes. Hands.",
            "relationship_delta": "Mutual recognition of lethality.",
            "plot_function": "Climax as pure tension.",
            "emotional_spine": "Dreadful patience.",
            "characters": ["MAN A", "MAN B", "MAN C"],
            "structural_beat": "Finale",
            "act": 3,
            "tags": ["standoff", "ECU eyes", "silence"],
        }],
        "shot_moments": [
            {
                "idx": 0, "scene_idx": 0, "scale": "ECU", "subject": "EYES",
                "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "EXT.",
                "location": "PLAZA", "time_of_day": "DAY",
                "action_text": "Hard cut between eyes; no wide until the draw.",
                "characters": ["MAN A"], "mood": "mythic heat", "dialogue": [],
            },
            {
                "idx": 1, "scene_idx": 0, "scale": "CU", "subject": "HAND ON HOLSTER",
                "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "EXT.",
                "location": "PLAZA", "time_of_day": "DAY",
                "action_text": "Fingers twitch above leather.",
                "characters": ["MAN B"], "mood": "coil", "dialogue": [],
            },
        ],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Standoff; audience expects a wide master.",
            "decision": "Stay in ECU eyes and hands; withhold the wide until the draw.",
            "rationale": "Geography is already known; tension lives in micro-motion.",
            "director": "Sergio Leone",
            "tags": ["ECU", "withhold wide", "standoff"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "sci-fi-airlock",
            "title": "Airlock (synthetic S-tier)",
            "year": 2013,
            "directors": ["Denis Villeneuve"],
            "genres": ["sci-fi", "thriller", "drama"],
            "medium": "short",
            "tier": "S",
            "theme": "Human scale against the void",
            "logline": "A decision at an airlock is made in silence and geometry.",
            "plot_summary": "Wide negative space; faces small against machinery.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "INT. AIRLOCK - NIGHT",
            "title": "Seal",
            "what_happens": "ASTRONAUT pauses at the hatch. Warning lights. They seal it.",
            "relationship_delta": "Duty over attachment.",
            "plot_function": "Irreversible choice.",
            "emotional_spine": "Quiet sacrifice.",
            "characters": ["ASTRONAUT"],
            "structural_beat": "All Is Lost",
            "act": 2,
            "tags": ["airlock", "wide negative space"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "EWS", "subject": "AIRLOCK CHAMBER",
            "angle": "HIGH ANGLE", "move": "STATIC", "int_ext": "INT.",
            "location": "AIRLOCK", "time_of_day": "NIGHT",
            "action_text": "Human figure tiny in the chamber; light bands.",
            "characters": ["ASTRONAUT"], "mood": "clinical awe", "dialogue": [],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Emotional peak in sci-fi; temptation to go CU on tears.",
            "decision": "Extreme wide; keep the human small against systems.",
            "rationale": "Scale is the emotion. Tears are smaller than the void.",
            "director": "Denis Villeneuve",
            "tags": ["EWS", "scale", "sci-fi"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "romcom-meet-cute",
            "title": "Meet Cute Door (synthetic A-tier)",
            "year": 2003,
            "directors": ["Nancy Meyers"],
            "genres": ["romance", "comedy"],
            "medium": "short",
            "tier": "A",
            "theme": "Warmth as design",
            "logline": "Two people collide at a doorway carrying too much.",
            "plot_summary": "Soft light, two-shot, prop comedy, genuine eye contact.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "EXT. BOOKSHOP - DAY",
            "title": "Collision",
            "what_happens": "SHE exits with books; HE enters; paperbacks rain.",
            "relationship_delta": "Strangers become story.",
            "plot_function": "Catalyst meet-cute.",
            "emotional_spine": "Embarrassed delight.",
            "characters": ["SHE", "HE"],
            "structural_beat": "Catalyst",
            "act": 1,
            "tags": ["meet-cute", "two-shot", "props"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "2-SHOT", "subject": "DOORWAY",
            "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "EXT.",
            "location": "BOOKSHOP", "time_of_day": "DAY",
            "action_text": "Hold both in frame through the spill and the laugh.",
            "characters": ["SHE", "HE"], "mood": "golden, warm", "dialogue": [
                {"character": "SHE", "text": "Sorry—", "parenthetical": ""},
                {"character": "HE", "text": "No, I— wow.", "parenthetical": ""},
            ],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Meet-cute; coverage temptation to cut singles.",
            "decision": "Hold a warm two-shot through the spill; cut singles only after the laugh.",
            "rationale": "Chemistry needs shared frame time.",
            "director": "Nancy Meyers",
            "tags": ["2-SHOT", "meet-cute", "hold"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "war-trench-letter",
            "title": "Trench Letter (synthetic S-tier)",
            "year": 1998,
            "directors": ["Terrence Malick"],
            "genres": ["war", "drama"],
            "medium": "short",
            "tier": "S",
            "theme": "Grace inside violence",
            "logline": "A soldier reads a letter while the world burns off-frame.",
            "plot_summary": "Natural light, voiceover adjacency, nature cutaways.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "EXT. TRENCH - DAWN",
            "title": "Letter",
            "what_happens": "SOLDIER reads. Smoke. A bird. Distant guns.",
            "relationship_delta": "Home vs now.",
            "plot_function": "Humanize before the charge.",
            "emotional_spine": "Tender dread.",
            "characters": ["SOLDIER"],
            "structural_beat": "Dark Night of the Soul",
            "act": 2,
            "tags": ["letter", "nature cutaway", "voice"],
        }],
        "shot_moments": [
            {
                "idx": 0, "scene_idx": 0, "scale": "MCU", "subject": "SOLDIER",
                "angle": "EYE LEVEL", "move": "HANDHELD", "int_ext": "EXT.",
                "location": "TRENCH", "time_of_day": "DAWN",
                "action_text": "Soft handheld on face and letter; wind on paper.",
                "characters": ["SOLDIER"], "mood": "golden mud", "dialogue": [],
            },
            {
                "idx": 1, "scene_idx": 0, "scale": "INSERT", "subject": "GRASS",
                "angle": "LOW ANGLE", "move": "STATIC", "int_ext": "EXT.",
                "location": "FIELD", "time_of_day": "DAWN",
                "action_text": "Cut to grass tips against sky — peace as counterpoint.",
                "characters": [], "mood": "transcendent", "dialogue": [],
            },
        ],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 1,
            "situation": "War drama; pressure to stay on violence.",
            "decision": "Cut from the letter to nature insert; let voice hold.",
            "rationale": "Grace is the point; the cutaway is the thesis.",
            "director": "Terrence Malick",
            "tags": ["insert", "nature", "counterpoint"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "noir-blinds",
            "title": "Venetian Blinds (synthetic S-tier)",
            "year": 1944,
            "directors": ["Billy Wilder"],
            "genres": ["noir", "crime", "drama"],
            "medium": "short",
            "tier": "S",
            "theme": "Desire as trap",
            "logline": "A private eye listens; light cuts his face into bars.",
            "plot_summary": "Hard light, shadow bars, voice from the dark half.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "INT. OFFICE - NIGHT",
            "title": "The offer",
            "what_happens": "CLIENT in shadow. DETECTIVE lit by blinds. A deal.",
            "relationship_delta": "Temptation accepted.",
            "plot_function": "Deal with the devil.",
            "emotional_spine": "Cynical heat.",
            "characters": ["DETECTIVE", "CLIENT"],
            "structural_beat": "Catalyst",
            "act": 1,
            "tags": ["blinds", "shadow", "noir"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "MS", "subject": "DETECTIVE AT DESK",
            "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "INT.",
            "location": "OFFICE", "time_of_day": "NIGHT",
            "action_text": "Blind shadows stripe the face; client mostly silhouette.",
            "characters": ["DETECTIVE", "CLIENT"], "mood": "venetian noir",
            "dialogue": [
                {"character": "CLIENT", "text": "I need someone who doesn't mind dirt.", "parenthetical": ""},
            ],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Moral compromise scene in noir.",
            "decision": "Light the hero through blinds; keep the tempter in silhouette.",
            "rationale": "The bars are already on his face before he says yes.",
            "director": "Billy Wilder",
            "tags": ["blinds", "silhouette", "noir lighting"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "animation-squash",
            "title": "Chase Squash (synthetic A-tier)",
            "year": 1957,
            "directors": ["Chuck Jones"],
            "genres": ["animation", "comedy"],
            "medium": "short",
            "tier": "A",
            "theme": "Physics as character",
            "logline": "A chase ends in a pose held for a perfect beat.",
            "plot_summary": "Anticipation, smash, hold, blink.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "EXT. DESERT ROAD - DAY",
            "title": "Stop",
            "what_happens": "CHASER skids; dust; held pose; eyes blink once.",
            "relationship_delta": "Predator vs pride.",
            "plot_function": "Comic button.",
            "emotional_spine": "Deflated fury.",
            "characters": ["CHASER"],
            "structural_beat": "Fun and Games",
            "act": 2,
            "tags": ["hold pose", "anticipation", "button"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "WS", "subject": "ROAD",
            "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "EXT.",
            "location": "DESERT ROAD", "time_of_day": "DAY",
            "action_text": "Wide enough for the skid path; hold the final pose.",
            "characters": ["CHASER"], "mood": "graphic, flat sun", "dialogue": [],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Cartoon chase ending; temptation to cut away early.",
            "decision": "Hold the wide pose one beat longer than comfortable; blink is the button.",
            "rationale": "Comedy timing is duration, not coverage.",
            "director": "Chuck Jones",
            "tags": ["hold", "timing", "wide"],
            "phase": "shotlist",
        }],
    },
    {
        "work": {
            "slug": "doc-interview-offset",
            "title": "Offset Interview (synthetic A-tier)",
            "year": 2015,
            "directors": ["Errol Morris"],
            "genres": ["documentary", "drama"],
            "medium": "short",
            "tier": "A",
            "theme": "Truth in the glance away",
            "logline": "A subject tells a story while looking just off the lens.",
            "plot_summary": "Interrotron adjacency; hold through the hesitation.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "INT. INTERVIEW ROOM - DAY",
            "title": "The glance",
            "what_happens": "SUBJECT speaks, then stops. Eyes drift. Resume.",
            "relationship_delta": "Audience as confessor.",
            "plot_function": "Reveal by omission.",
            "emotional_spine": "Uneasy honesty.",
            "characters": ["SUBJECT"],
            "structural_beat": "Debate",
            "act": 1,
            "tags": ["interview", "hold", "eyes"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "CU", "subject": "SUBJECT",
            "angle": "EYE LEVEL", "move": "STATIC", "int_ext": "INT.",
            "location": "INTERVIEW ROOM", "time_of_day": "DAY",
            "action_text": "Do not cut on the pause; the silence is the answer.",
            "characters": ["SUBJECT"], "mood": "flat soft key", "dialogue": [
                {"character": "SUBJECT", "text": "I don't remember saying that.", "parenthetical": "after a beat"},
            ],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Interview; editor wants to trim the pause.",
            "decision": "Hold CU through the full hesitation; cut only after the next sentence starts.",
            "rationale": "The glance away is the documentary event.",
            "director": "Errol Morris",
            "tags": ["hold silence", "CU", "interview"],
            "phase": "cut",
        }],
    },
    {
        "work": {
            "slug": "musical-match-cut",
            "title": "Match Cut Chorus (synthetic A-tier)",
            "year": 2001,
            "directors": ["Baz Luhrmann"],
            "genres": ["musical", "romance", "drama"],
            "medium": "short",
            "tier": "A",
            "theme": "Emotion as velocity",
            "logline": "A chorus builds across three locations by match-cutting gesture.",
            "plot_summary": "Kinetic montage bound by arm movement and tempo.",
            "source": "seed:hand-labeled",
        },
        "scene_cards": [{
            "idx": 0,
            "slugline": "INT./EXT. CITY - NIGHT",
            "title": "Chorus",
            "what_happens": "SINGER raises an arm; match to dancer; match to crowd.",
            "relationship_delta": "Private feeling becomes public.",
            "plot_function": "Musical peak.",
            "emotional_spine": "Exultant ache.",
            "characters": ["SINGER", "DANCER", "CROWD"],
            "structural_beat": "Finale",
            "act": 3,
            "tags": ["match cut", "montage", "musical"],
        }],
        "shot_moments": [{
            "idx": 0, "scene_idx": 0, "scale": "MS", "subject": "ARM RAISE",
            "angle": "LOW ANGLE", "move": "WHIP PAN", "int_ext": "INT./EXT.",
            "location": "CITY", "time_of_day": "NIGHT",
            "action_text": "Match the gesture across spaces; tempo locks the cut.",
            "characters": ["SINGER"], "mood": "saturated neon", "dialogue": [],
        }],
        "decision_digests": [{
            "scene_idx": 0, "shot_idx": 0,
            "situation": "Musical montage; risk of chaos.",
            "decision": "Bind locations with one repeated gesture; cut on the beat of the arm.",
            "rationale": "Unity is kinetic, not geographic.",
            "director": "Baz Luhrmann",
            "tags": ["match cut", "gesture", "tempo"],
            "phase": "shotlist",
        }],
    },
]
